export enum orderParamsEnum {
    page = 'page',
    order = 'order',
    name = 'name',
    surname = 'surname',
    email = 'email',
    phone = 'phone',
    age = 'age',
    course = 'course',
    course_format = 'course_format',
    course_type = 'course_type',
    alreadyPaid = 'alreadyPaid',
    sum = 'sum',
    status = 'status',
    manager = 'manager',
    group = 'group',
    end_date = 'end_date',
    start_date = 'start_date',
    my='my'
}
